In [1]:
import numpy as np


In [2]:
# 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та
# виведіть його значення.

vector = np.arange(1, 11)
print("Одновимірний масив:", vector)


Одновимірний масив: [ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та
# виведіть його значення.

matrix_3x3_zeros = np.zeros((3, 3), dtype=np.int8)
print("Двовимірний масив 3x3, заповнений нулями:\n", matrix_3x3_zeros)


Двовимірний масив 3x3, заповнений нулями:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в
# діапазоні від 1 до 10 та виведіть його значення.

matrix_5x5_random_int = np.random.randint(1, 11, size=(5, 5))
print("Масив розміром 5x5, заповнений випадковими цілими числами:\n",
      matrix_5x5_random_int)


Масив розміром 5x5, заповнений випадковими цілими числами:
 [[ 2  1  2  9  5]
 [ 7  7  7  7  4]
 [ 3  1  5  5  2]
 [ 1  2  8  3  7]
 [ 4 10  2  8  8]]


In [5]:
# 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в
# діапазоні від 0 до 1 та виведіть його значення.

matrix_4x4_random_float = np.random.rand(4, 4)
print("Масив розміром 4x4, заповнений випадковими дійсними числами:\n",
      matrix_4x4_random_float)


Масив розміром 4x4, заповнений випадковими дійсними числами:
 [[0.01089493 0.82779134 0.75393516 0.05817137]
 [0.98101675 0.46201696 0.12037291 0.19915909]
 [0.48321836 0.95580339 0.36577372 0.99219514]
 [0.33404838 0.28493476 0.89642432 0.04198891]]


In [6]:
# 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими
# числами в діапазоні від 1 до 10 та виконайте на них поелементні операції
# додавання, віднімання та множення.

vector1 = np.random.randint(1, 11, size=5)
vector2 = np.random.randint(1, 11, size=5)
print("Вектор 1:", vector1)
print("Вектор 2:", vector2)

addition = vector1 + vector2
subtraction = vector1 - vector2
multiplication = vector1 * vector2

print("Додавання:", addition)
print("Віднімання:", subtraction)
print("Множення:", multiplication)


Вектор 1: [3 8 8 8 5]
Вектор 2: [ 7  8  1 10  1]
Додавання: [10 16  9 18  6]
Віднімання: [-4  0  7 -2  4]
Множення: [21 64  8 80  5]


In [7]:
# 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх
# скалярний добуток.

vector1 = np.random.rand(7)
vector2 = np.random.rand(7)
dot_product = np.dot(vector1, vector2)
print("Скалярний добуток:", dot_product)

Скалярний добуток: 1.434105816123309


In [8]:
# 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими
# числами в діапазоні від 1 до 10 та перемножте їх між собою.

matrix_2x2 = np.random.randint(1, 11, size=(2, 2))
matrix_2x3 = np.random.randint(1, 11, size=(2, 3))
matrix_product = np.dot(matrix_2x2, matrix_2x3)
print("Матриця 2x2:\n", matrix_2x2)
print("Матриця 2x3:\n", matrix_2x3)
print("Добуток матриць:\n", matrix_product)


Матриця 2x2:
 [[1 1]
 [3 9]]
Матриця 2x3:
 [[10  3  2]
 [10  5  9]]
Добуток матриць:
 [[ 20   8  11]
 [120  54  87]]


In [9]:
# 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в
# діапазоні від 1 до 10 та знайдіть її обернену матрицю.

matrix_3x3 = np.random.randint(1, 11, size=(3, 3))
inverse_matrix = np.linalg.inv(matrix_3x3)
print("Матриця 3x3:\n", matrix_3x3)
print("Обернена матриця:\n", inverse_matrix)


Матриця 3x3:
 [[ 9  1  8]
 [10  7  4]
 [ 7  1  3]]
Обернена матриця:
 [[-0.10559006 -0.0310559   0.32298137]
 [ 0.01242236  0.18012422 -0.27329193]
 [ 0.24223602  0.01242236 -0.32919255]]


In [10]:
# 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
# діапазоні від 0 до 1 та транспонуйте її.

matrix_4x4 = np.random.rand(4, 4)
transposed_matrix = matrix_4x4.T
print("Матриця 4x4:\n", matrix_4x4)
print("Транспонована матриця:\n", transposed_matrix)


Матриця 4x4:
 [[1.39630394e-01 5.21184896e-01 5.48817957e-01 8.84251547e-01]
 [5.86344287e-01 9.33542251e-01 5.07793893e-01 8.27346833e-01]
 [5.18422844e-01 6.57035113e-01 7.82483520e-01 7.46918043e-02]
 [2.59750580e-01 4.65614240e-01 3.47838864e-04 8.77269670e-01]]
Транспонована матриця:
 [[1.39630394e-01 5.86344287e-01 5.18422844e-01 2.59750580e-01]
 [5.21184896e-01 9.33542251e-01 6.57035113e-01 4.65614240e-01]
 [5.48817957e-01 5.07793893e-01 7.82483520e-01 3.47838864e-04]
 [8.84251547e-01 8.27346833e-01 7.46918043e-02 8.77269670e-01]]


In [11]:
# 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими
# цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

matrix_3x4 = np.random.randint(1, 11, size=(3, 4))
vector_4 = np.random.randint(1, 11, size=4)
product_matrix_vector = np.dot(matrix_3x4, vector_4)
print("Матриця 3x4:\n", matrix_3x4)
print("Вектор розміром 4:", vector_4)
print("Добуток матриці та вектора:", product_matrix_vector)


Матриця 3x4:
 [[ 8  3  4 10]
 [ 2  4  1  8]
 [ 4 10  7  2]]
Вектор розміром 4: [7 5 3 5]
Добуток матриці та вектора: [133  77 109]


In [12]:
# 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими
# дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

matrix_2x3 = np.random.rand(2, 3)
vector_3 = np.random.rand(3)
product_matrix_vector = np.dot(matrix_2x3, vector_3)
print("Матриця 2x3:\n", matrix_2x3)
print("Вектор розміром 3:", vector_3)
print("Добуток матриці та вектора:", product_matrix_vector)


Матриця 2x3:
 [[0.76851134 0.05389267 0.1561725 ]
 [0.09372647 0.49179065 0.3271378 ]]
Вектор розміром 3: [0.23275499 0.76396991 0.10184376]
Добуток матриці та вектора: [0.23595242 0.43084551]


In [13]:
# 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в
# діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

matrix1_2x2 = np.random.randint(1, 11, size=(2, 2))
matrix2_2x2 = np.random.randint(1, 11, size=(2, 2))
elementwise_product = matrix1_2x2 * matrix2_2x2
print("Матриця 1 (2x2):\n", matrix1_2x2)
print("Матриця 2 (2x2):\n", matrix2_2x2)
print("Поелементне множення:\n", elementwise_product)


Матриця 1 (2x2):
 [[7 4]
 [4 4]]
Матриця 2 (2x2):
 [[6 8]
 [6 7]]
Поелементне множення:
 [[42 32]
 [24 28]]


In [14]:
# 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в
# діапазоні від 1 до 10 та знайдіть їх добуток.

matrix1_2x2 = np.random.randint(1, 11, size=(2, 2))
matrix2_2x2 = np.random.randint(1, 11, size=(2, 2))
matrix_product = np.dot(matrix1_2x2, matrix2_2x2)
print("Матриця 1 (2x2):\n", matrix1_2x2)
print("Матриця 2 (2x2):\n", matrix2_2x2)
print("Добуток матриць:\n", matrix_product)


Матриця 1 (2x2):
 [[ 9  5]
 [ 1 10]]
Матриця 2 (2x2):
 [[10  5]
 [ 9  5]]
Добуток матриць:
 [[135  70]
 [100  55]]


In [15]:
# 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в
# діапазоні від 1 до 100 та знайдіть суму елементів матриці.

matrix_5x5 = np.random.randint(1, 101, size=(5, 5))
sum_elements = np.sum(matrix_5x5)
print("Матриця 5x5:\n", matrix_5x5)
print("Сума елементів матриці:", sum_elements)


Матриця 5x5:
 [[20 55 13 45 58]
 [44 19 97 59 63]
 [44 53  6 62 47]
 [32 39 50 83 67]
 [ 9 69 88 66 13]]
Сума елементів матриці: 1201


In [16]:
# 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в
# діапазоні від 1 до 10 та знайдіть їхню різницю.

matrix1_4x4 = np.random.randint(1, 11, size=(4, 4))
matrix2_4x4 = np.random.randint(1, 11, size=(4, 4))
difference_matrix = matrix1_4x4 - matrix2_4x4
print("Матриця 1 (4x4):\n", matrix1_4x4)
print("Матриця 2 (4x4):\n", matrix2_4x4)
print("Різниця матриць:\n", difference_matrix)


Матриця 1 (4x4):
 [[7 3 5 7]
 [6 4 5 3]
 [1 3 6 6]
 [4 2 8 2]]
Матриця 2 (4x4):
 [[ 8  6 10  6]
 [ 5  5  9  9]
 [ 3 10 10  1]
 [ 2  9  6  9]]
Різниця матриць:
 [[-1 -3 -5  1]
 [ 1 -1 -4 -6]
 [-2 -7 -4  5]
 [ 2 -7  2 -7]]


In [17]:
# 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
# діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів
# кожного рядка матриці.

matrix_3x3 = np.random.rand(3, 3)
row_sum = np.sum(matrix_3x3, axis=1)
print("Матриця 3x3:\n", matrix_3x3)
print("Сума елементів кожного рядка:", row_sum)


Матриця 3x3:
 [[0.42107078 0.21102942 0.06086761]
 [0.16459197 0.80416985 0.07956736]
 [0.16619808 0.1542244  0.68059465]]
Сума елементів кожного рядка: [0.69296781 1.04832919 1.00101713]


In [18]:
# 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з
# квадратами цих чисел.

matrix_3x4 = np.random.randint(1, 11, size=(3, 4))
matrix_square = np.square(matrix_3x4)
print("Матриця 3x4:\n", matrix_3x4)
print("Квадрат елементів матриці:\n", matrix_square)


Матриця 3x4:
 [[ 5  8  6  5]
 [ 1 10  9  4]
 [ 7  8  4  5]]
Квадрат елементів матриці:
 [[ 25  64  36  25]
 [  1 100  81  16]
 [ 49  64  16  25]]


In [19]:
# 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в
# діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

vector_4 = np.random.randint(1, 51, size=4)
vector_sqrt = np.sqrt(vector_4)
print("Вектор розміром 4:", vector_4)
print("Квадратний корінь вектора:", vector_sqrt)


Вектор розміром 4: [14 38 10 20]
Квадратний корінь вектора: [3.74165739 6.164414   3.16227766 4.47213595]
